// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyIOT.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyIOT.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209062252_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyIOT.Api.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("access_token");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("AccessToken")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_access_token");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("MyIOT.Api.Models.DeviceAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_device_attributes");

                    b.HasIndex("DeviceId", "Key", "Scope")
                        .IsUnique()
                        .HasDatabaseName("ix_device_attributes_device_id_key_scope");

                    b.ToTable("device_attributes", (string)null);
                });

            modelBuilder.Entity("MyIOT.Api.Models.TelemetryRecord", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("DeviceId", "Key", "Timestamp")
                        .HasName("pk_telemetry");

                    b.HasIndex("DeviceId", "Timestamp")
                        .HasDatabaseName("ix_telemetry_device_id_timestamp");

                    b.ToTable("telemetry", (string)null);
                });

            modelBuilder.Entity("MyIOT.Api.Models.DeviceAttribute", b =>
                {
                    b.HasOne("MyIOT.Api.Models.Device", "Device")
                        .WithMany("Attributes")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_attributes_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MyIOT.Api.Models.TelemetryRecord", b =>
                {
                    b.HasOne("MyIOT.Api.Models.Device", "Device")
                        .WithMany("TelemetryRecords")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telemetry_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MyIOT.Api.Models.Device", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("TelemetryRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
